# Generated by Django 3.1.3 on 2020-11-10 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.affiliate'),
        ),
    ]
